apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
spec:
  selector:
    app: node-webapp  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 3000 
  type: LoadBalancer