trigger:
  branches:
    include:
      - main 

pr:
  branches:
    include:
      - main 
resources:
- repo: self

variables:

  
  dockerRegistryServiceConnection: '164f9470-7f09-4070-a7aa-cb59ef7c3513'
  imageRepository: 'devimage'
  containerRegistry: 'devacr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'devacr9ac0-auth'

  
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build for dev stage
  jobs:
  - job: Build
    displayName: Build for stage
    pool:
      name: Default
      demands:
        - agent.name -equals WSL
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy for dev
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Default
      demands:
        - agent.name -equals WSL
    environment: 'nodejsapp.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/dev-deploy.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

